/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  announcement?: string;
  tagline?: string;
  description?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  brandIntro?: string;
  brandStory?: Array<string>;
  brandPhilosophy?: Array<string>;
  phoneDisplay?: string;
  phoneE164?: string;
  whatsappNumber?: string;
  email?: string;
  address?: string;
  openingHours?: string;
  mapsHref?: string;
  socialLinks?: Array<{
    _key: string;
  } & Link>;
  bookingLabel?: string;
  bookingHref?: string;
  bookingTimeSlots?: Array<string>;
  bookingTreatmentOptions?: Array<string>;
  clinicPhilosophy?: string;
  licenceStatement?: string;
  licenceNumber?: string;
  safetyStatement?: string;
  highlights?: Array<{
    _key: string;
  } & ClinicHighlight>;
  safetyProtocols?: Array<{
    _key: string;
  } & SafetyProtocol>;
  internationalPoints?: Array<{
    _key: string;
  } & InternationalPoint>;
  clinicFaqs?: Array<{
    _key: string;
  } & FaqItem>;
  glanceTitle?: string;
  glanceLabels?: {
    startingFrom?: string;
    treatmentTime?: string;
    anaesthesia?: string;
    downtime?: string;
    initialResult?: string;
    fullResult?: string;
    category?: string;
    performedBy?: string;
  };
  glanceUnpublished?: string;
  bookTreatmentLabel?: string;
  sectionHeadings?: {
    aboutEyebrow?: string;
    journeyEyebrow?: string;
    journeyTitle?: string;
    safetyEyebrow?: string;
    safetyTitle?: string;
    faqEyebrow?: string;
    faqTitle?: string;
    resultsTitle?: string;
    relatedEyebrow?: string;
  };
  defaultSeo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  quote?: string;
  source?: "Google" | "Fresha" | "Other";
  featured?: boolean;
  treatments?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "treatment";
  }>;
  order?: number;
};

export type Doctor = {
  _id: string;
  _type: "doctor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  title?: string;
  photo?: ImageWithAlt;
  bio?: Array<string>;
  registrationNumber?: string;
  registryUrl?: string;
  order?: number;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PricingSection = {
  _id: string;
  _type: "pricingSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "facial-enhancement" | "skin-treatments" | "body-treatments" | "hair-booster";
  order?: number;
  groups?: Array<{
    _key: string;
  } & PriceGroup>;
};

export type Treatment = {
  _id: string;
  _type: "treatment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  h1?: string;
  slug?: Slug;
  path?: string;
  category?: "facial-enhancement" | "skin-treatments" | "body-treatments" | "hair-booster";
  shortDescription?: string;
  intro?: string;
  image?: ImageWithAlt;
  imagePosition?: "object-center" | "object-top" | "object-bottom" | "object-left" | "object-right";
  featuredOnHomepage?: boolean;
  featuredOrder?: number;
  mostPopular?: boolean;
  treatmentTime?: string;
  treatmentTimeShort?: string;
  anaesthesia?: string;
  downtime?: string;
  initialResult?: string;
  fullResult?: string;
  performedBy?: string;
  startingPrice?: number;
  priceUnit?: string;
  priceGroups?: Array<{
    _key: string;
  } & PriceGroup>;
  popularAreasTitle?: string;
  popularAreas?: Array<string>;
  journey?: Array<{
    _key: string;
  } & JourneyStep>;
  sections?: Array<{
    _key: string;
  } & TreatmentSection>;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: ImageWithAlt;
  body?: PortableText;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  seo?: Seo;
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    blank?: boolean;
    _type: "textLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & ImageWithAlt>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  path?: string;
  sections?: Array<{
    _key: string;
  } & HeroSection | {
    _key: string;
  } & RichTextSection | {
    _key: string;
  } & SplitContentSection | {
    _key: string;
  } & FeatureGridSection | {
    _key: string;
  } & GallerySection | {
    _key: string;
  } & FaqSection | {
    _key: string;
  } & CtaSection | {
    _key: string;
  } & CollectionSection | {
    _key: string;
  } & CuratedSection | {
    _key: string;
  } & PricingPromiseSection | {
    _key: string;
  } & CategoryNavSection | {
    _key: string;
  } & TaglineSection | {
    _key: string;
  } & DisclaimerSection | {
    _key: string;
  } & ResultsNavSection>;
  seo?: Seo;
};

export type ResultsNavSection = {
  _type: "resultsNavSection";
  label?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type DisclaimerSection = {
  _type: "disclaimerSection";
  lead?: string;
  text?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type TaglineSection = {
  _type: "taglineSection";
  text?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type CategoryNavSection = {
  _type: "categoryNavSection";
  label?: string;
  anchor?: string;
  isHidden?: boolean;
};

export type PricingPromiseSection = {
  _type: "pricingPromiseSection";
  eyebrow?: string;
  title?: string;
  description?: string;
  points?: Array<{
    label?: string;
    detail?: string;
    _type: "pricingPromisePoint";
    _key: string;
  }>;
  anchor?: string;
  isHidden?: boolean;
};

export type CuratedSection = {
  _type: "curatedSection";
  component?: "homeHero" | "brandStory" | "partners" | "treatments" | "treatmentHighlights" | "whyUs" | "doctors" | "testimonials" | "clinicExperience" | "internationalPatients" | "homeFaq" | "blogTeaser" | "booking";
  anchor?: string;
  isHidden?: boolean;
};

export type CollectionSection = {
  _type: "collectionSection";
  source?: "treatmentsDirectory" | "blogDirectory" | "pricingDirectory" | "bookingForm" | "giftCardForm";
  eyebrow?: string;
  title?: string;
  description?: string;
  tone?: "paper" | "white" | "wash" | "blush" | "lime" | "brown";
  anchor?: string;
  isHidden?: boolean;
};

export type CtaSection = {
  _type: "ctaSection";
  eyebrow?: string;
  title?: string;
  text?: string;
  primaryAction?: Link;
  secondaryAction?: Link;
  tone?: "lime" | "brown" | "blush";
  anchor?: string;
  isHidden?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
  external?: boolean;
};

export type FaqSection = {
  _type: "faqSection";
  eyebrow?: string;
  title?: string;
  description?: string;
  items?: Array<{
    _key: string;
  } & FaqItem>;
  tone?: "light" | "dark";
  anchor?: string;
  isHidden?: boolean;
};

export type GallerySection = {
  _type: "gallerySection";
  eyebrow?: string;
  title?: string;
  description?: string;
  images?: Array<{
    _key: string;
  } & ImageWithAlt>;
  tone?: "paper" | "white" | "wash" | "blush" | "lime" | "brown";
  anchor?: string;
  isHidden?: boolean;
};

export type FeatureGridSection = {
  _type: "featureGridSection";
  eyebrow?: string;
  title?: string;
  description?: string;
  items?: Array<{
    _key: string;
  } & FeatureItem>;
  columns?: 2 | 3 | 4;
  tone?: "paper" | "white" | "wash" | "blush" | "lime" | "brown";
  anchor?: string;
  isHidden?: boolean;
};

export type SplitContentSection = {
  _type: "splitContentSection";
  eyebrow?: string;
  title?: string;
  body?: PortableText;
  image?: ImageWithAlt;
  imageSide?: "left" | "right";
  action?: Link;
  tone?: "paper" | "white" | "wash" | "blush" | "lime" | "brown";
  anchor?: string;
  isHidden?: boolean;
};

export type RichTextSection = {
  _type: "richTextSection";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  body?: PortableText;
  align?: "left" | "center";
  width?: "narrow" | "standard";
  tone?: "paper" | "white" | "wash" | "blush" | "lime" | "brown";
  anchor?: string;
  isHidden?: boolean;
};

export type HeroSection = {
  _type: "heroSection";
  presentation?: "home" | "inner";
  eyebrow?: string;
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  primaryAction?: Link;
  secondaryAction?: Link;
  anchor?: string;
  isHidden?: boolean;
};

export type TreatmentSection = {
  _type: "treatmentSection";
  title?: string;
  blocks?: Array<{
    _key: string;
  } & TreatmentContentBlock>;
  points?: Array<string>;
};

export type TreatmentContentBlock = {
  _type: "treatmentContentBlock";
  heading?: string;
  paragraphs?: Array<string>;
};

export type PriceGroup = {
  _type: "priceGroup";
  title?: string;
  rows?: Array<{
    _key: string;
  } & PriceRow>;
  note?: string;
};

export type PriceRow = {
  _type: "priceRow";
  label?: string;
  price?: number;
  unit?: string;
  description?: string;
};

export type InternationalPoint = {
  _type: "internationalPoint";
  title?: string;
  note?: string;
};

export type SafetyProtocol = {
  _type: "safetyProtocol";
  title?: string;
  description?: string;
};

export type ClinicHighlight = {
  _type: "clinicHighlight";
  title?: string;
  tagline?: string;
  description?: string;
};

export type JourneyStep = {
  _type: "journeyStep";
  label?: string;
  duration?: string;
};

export type FeatureItem = {
  _type: "featureItem";
  title?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  note?: string;
  image?: ImageWithAlt;
  action?: Link;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: PortableText;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SiteSettings | Seo | Testimonial | Doctor | ImageWithAlt | Partner | SanityImageCrop | SanityImageHotspot | PricingSection | Treatment | Slug | Category | Post | PortableText | Page | ResultsNavSection | DisclaimerSection | TaglineSection | CategoryNavSection | PricingPromiseSection | CuratedSection | CollectionSection | CtaSection | Link | FaqSection | GallerySection | FeatureGridSection | SplitContentSection | RichTextSection | HeroSection | TreatmentSection | TreatmentContentBlock | PriceGroup | PriceRow | InternationalPoint | SafetyProtocol | ClinicHighlight | JourneyStep | FeatureItem | FaqItem | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: pageByPathQuery
// Query: *[_type == "page" && path == $path][0]{    _id,    _type,    title,    path,    seo {  title,  description,  image {  _type,  asset,  alt,  caption,  crop,  hotspot},  noIndex},    sections[] {  ...,  image {  _type,  asset,  alt,  caption,  crop,  hotspot},  images[] {  _type,  asset,  alt,  caption,  crop,  hotspot},  items[]{    ...,    image {  _type,  asset,  alt,  caption,  crop,  hotspot}  }}  }
export type PageByPathQueryResult = {
  _id: string;
  _type: "page";
  title: string | null;
  path: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
  sections: Array<{
    _key: string;
    _type: "categoryNavSection";
    label?: string;
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "collectionSection";
    source?: "blogDirectory" | "bookingForm" | "giftCardForm" | "pricingDirectory" | "treatmentsDirectory";
    eyebrow?: string;
    title?: string;
    description?: string;
    tone?: "blush" | "brown" | "lime" | "paper" | "wash" | "white";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "ctaSection";
    eyebrow?: string;
    title?: string;
    text?: string;
    primaryAction?: Link;
    secondaryAction?: Link;
    tone?: "blush" | "brown" | "lime";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "curatedSection";
    component?: "blogTeaser" | "booking" | "brandStory" | "clinicExperience" | "doctors" | "homeFaq" | "homeHero" | "internationalPatients" | "partners" | "testimonials" | "treatmentHighlights" | "treatments" | "whyUs";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "disclaimerSection";
    lead?: string;
    text?: string;
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "faqSection";
    eyebrow?: string;
    title?: string;
    description?: string;
    items: Array<{
      _key: string;
      _type: "faqItem";
      question?: string;
      answer?: PortableText;
      image: null;
    }> | null;
    tone?: "dark" | "light";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
  } | {
    _key: string;
    _type: "featureGridSection";
    eyebrow?: string;
    title?: string;
    description?: string;
    items: Array<{
      _key: string;
      _type: "featureItem";
      title?: string;
      text?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      note?: string;
      image: {
        _type: "imageWithAlt";
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
        alt: string | null;
        caption: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
      } | null;
      action?: Link;
    }> | null;
    columns?: 2 | 3 | 4;
    tone?: "blush" | "brown" | "lime" | "paper" | "wash" | "white";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
  } | {
    _key: string;
    _type: "gallerySection";
    eyebrow?: string;
    title?: string;
    description?: string;
    images: Array<{
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    }> | null;
    tone?: "blush" | "brown" | "lime" | "paper" | "wash" | "white";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    items: null;
  } | {
    _key: string;
    _type: "heroSection";
    presentation?: "home" | "inner";
    eyebrow?: string;
    title?: string;
    description?: string;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    primaryAction?: Link;
    secondaryAction?: Link;
    anchor?: string;
    isHidden?: boolean;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "pricingPromiseSection";
    eyebrow?: string;
    title?: string;
    description?: string;
    points?: Array<{
      label?: string;
      detail?: string;
      _type: "pricingPromisePoint";
      _key: string;
    }>;
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "resultsNavSection";
    label?: string;
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "richTextSection";
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    body?: PortableText;
    align?: "center" | "left";
    width?: "narrow" | "standard";
    tone?: "blush" | "brown" | "lime" | "paper" | "wash" | "white";
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "splitContentSection";
    eyebrow?: string;
    title?: string;
    body?: PortableText;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    imageSide?: "left" | "right";
    action?: Link;
    tone?: "blush" | "brown" | "lime" | "paper" | "wash" | "white";
    anchor?: string;
    isHidden?: boolean;
    images: null;
    items: null;
  } | {
    _key: string;
    _type: "taglineSection";
    text?: string;
    anchor?: string;
    isHidden?: boolean;
    image: null;
    images: null;
    items: null;
  }> | null;
} | null;
// Variable: allPagePathsQuery
// Query: *[_type == "page" && defined(path)].path
export type AllPagePathsQueryResult = Array<string>;
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,    excerpt,    coverImage {  _type,  asset,  alt,  caption,  crop,  hotspot},    publishedAt,    "categories": categories[]->{_id, title, "slug": slug.current},    body,    seo {  title,  description,  image {  _type,  asset,  alt,  caption,  crop,  hotspot},  noIndex}  }
export type PostBySlugQueryResult = {
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    _type: "imageWithAlt";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  publishedAt: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  body: PortableText | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | null;
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id,    _type,    title,    "slug": slug.current,    excerpt,    coverImage {  _type,  asset,  alt,  caption,  crop,  hotspot},    publishedAt,    "categories": categories[]->{_id, title, "slug": slug.current},    body,    seo {  title,  description,  image {  _type,  asset,  alt,  caption,  crop,  hotspot},  noIndex}  }
export type AllPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    _type: "imageWithAlt";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  publishedAt: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  body: PortableText | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;
// Variable: allPostSlugsQuery
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type AllPostSlugsQueryResult = Array<string | null>;
// Variable: allTreatmentsQuery
// Query: *[_type == "treatment" && defined(slug.current)] | order(name asc){    ...,    "slug": slug.current,    image {  _type,  asset,  alt,  caption,  crop,  hotspot},    seo {  title,  description,  image {  _type,  asset,  alt,  caption,  crop,  hotspot},  noIndex}  }
export type AllTreatmentsQueryResult = Array<{
  _id: string;
  _type: "treatment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  h1?: string;
  slug: string | null;
  path?: string;
  category?: "body-treatments" | "facial-enhancement" | "hair-booster" | "skin-treatments";
  shortDescription?: string;
  intro?: string;
  image: {
    _type: "imageWithAlt";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  imagePosition?: "object-bottom" | "object-center" | "object-left" | "object-right" | "object-top";
  featuredOnHomepage?: boolean;
  featuredOrder?: number;
  mostPopular?: boolean;
  treatmentTime?: string;
  treatmentTimeShort?: string;
  anaesthesia?: string;
  downtime?: string;
  initialResult?: string;
  fullResult?: string;
  performedBy?: string;
  startingPrice?: number;
  priceUnit?: string;
  priceGroups?: Array<{
    _key: string;
  } & PriceGroup>;
  popularAreasTitle?: string;
  popularAreas?: Array<string>;
  journey?: Array<{
    _key: string;
  } & JourneyStep>;
  sections?: Array<{
    _key: string;
  } & TreatmentSection>;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
}>;
// Variable: allPricingSectionsQuery
// Query: *[_type == "pricingSection"] | order(order asc, title asc){    _id,    _type,    title,    category,    order,    groups  }
export type AllPricingSectionsQueryResult = Array<{
  _id: string;
  _type: "pricingSection";
  title: string | null;
  category: "body-treatments" | "facial-enhancement" | "hair-booster" | "skin-treatments" | null;
  order: number | null;
  groups: Array<{
    _key: string;
  } & PriceGroup> | null;
}>;
// Variable: siteSettingsQuery
// Query: *[_id == "siteSettings"][0]{    ...,    defaultSeo {  title,  description,  image {  _type,  asset,  alt,  caption,  crop,  hotspot},  noIndex}  }
export type SiteSettingsQueryResult = {
  _id: "siteSettings";
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "doctor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  title?: string;
  photo?: ImageWithAlt;
  bio?: Array<string>;
  registrationNumber?: string;
  registryUrl?: string;
  order?: number;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  path?: string;
  sections?: Array<{
    _key: string;
  } & CategoryNavSection | {
    _key: string;
  } & CollectionSection | {
    _key: string;
  } & CtaSection | {
    _key: string;
  } & CuratedSection | {
    _key: string;
  } & DisclaimerSection | {
    _key: string;
  } & FaqSection | {
    _key: string;
  } & FeatureGridSection | {
    _key: string;
  } & GallerySection | {
    _key: string;
  } & HeroSection | {
    _key: string;
  } & PricingPromiseSection | {
    _key: string;
  } & ResultsNavSection | {
    _key: string;
  } & RichTextSection | {
    _key: string;
  } & SplitContentSection | {
    _key: string;
  } & TaglineSection>;
  seo?: Seo;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: ImageWithAlt;
  body?: PortableText;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  seo?: Seo;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "pricingSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "body-treatments" | "facial-enhancement" | "hair-booster" | "skin-treatments";
  order?: number;
  groups?: Array<{
    _key: string;
  } & PriceGroup>;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  announcement?: string;
  tagline?: string;
  description?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  brandIntro?: string;
  brandStory?: Array<string>;
  brandPhilosophy?: Array<string>;
  phoneDisplay?: string;
  phoneE164?: string;
  whatsappNumber?: string;
  email?: string;
  address?: string;
  openingHours?: string;
  mapsHref?: string;
  socialLinks?: Array<{
    _key: string;
  } & Link>;
  bookingLabel?: string;
  bookingHref?: string;
  bookingTimeSlots?: Array<string>;
  bookingTreatmentOptions?: Array<string>;
  clinicPhilosophy?: string;
  licenceStatement?: string;
  licenceNumber?: string;
  safetyStatement?: string;
  highlights?: Array<{
    _key: string;
  } & ClinicHighlight>;
  safetyProtocols?: Array<{
    _key: string;
  } & SafetyProtocol>;
  internationalPoints?: Array<{
    _key: string;
  } & InternationalPoint>;
  clinicFaqs?: Array<{
    _key: string;
  } & FaqItem>;
  glanceTitle?: string;
  glanceLabels?: {
    startingFrom?: string;
    treatmentTime?: string;
    anaesthesia?: string;
    downtime?: string;
    initialResult?: string;
    fullResult?: string;
    category?: string;
    performedBy?: string;
  };
  glanceUnpublished?: string;
  bookTreatmentLabel?: string;
  sectionHeadings?: {
    aboutEyebrow?: string;
    journeyEyebrow?: string;
    journeyTitle?: string;
    safetyEyebrow?: string;
    safetyTitle?: string;
    faqEyebrow?: string;
    faqTitle?: string;
    resultsTitle?: string;
    relatedEyebrow?: string;
  };
  defaultSeo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "imageWithAlt";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      alt: string | null;
      caption: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    noIndex: boolean | null;
  } | null;
} | {
  _id: "siteSettings";
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  quote?: string;
  source?: "Fresha" | "Google" | "Other";
  featured?: boolean;
  treatments?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "treatment";
  }>;
  order?: number;
  defaultSeo: null;
} | {
  _id: "siteSettings";
  _type: "treatment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  h1?: string;
  slug?: Slug;
  path?: string;
  category?: "body-treatments" | "facial-enhancement" | "hair-booster" | "skin-treatments";
  shortDescription?: string;
  intro?: string;
  image?: ImageWithAlt;
  imagePosition?: "object-bottom" | "object-center" | "object-left" | "object-right" | "object-top";
  featuredOnHomepage?: boolean;
  featuredOrder?: number;
  mostPopular?: boolean;
  treatmentTime?: string;
  treatmentTimeShort?: string;
  anaesthesia?: string;
  downtime?: string;
  initialResult?: string;
  fullResult?: string;
  performedBy?: string;
  startingPrice?: number;
  priceUnit?: string;
  priceGroups?: Array<{
    _key: string;
  } & PriceGroup>;
  popularAreasTitle?: string;
  popularAreas?: Array<string>;
  journey?: Array<{
    _key: string;
  } & JourneyStep>;
  sections?: Array<{
    _key: string;
  } & TreatmentSection>;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  seo?: Seo;
  defaultSeo: null;
} | null;
// Variable: resultGalleriesQuery
// Query: *[_id == "page.before-after"][0].sections[_type == "gallerySection"]{    anchor,    images[] {  _type,  asset,  alt,  caption,  crop,  hotspot}  }
export type ResultGalleriesQueryResult = Array<{
  anchor: string | null;
  images: Array<{
    _type: "imageWithAlt";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
}> | Array<never> | null;
// Variable: allPartnersQuery
// Query: *[_type == "partner"] | order(order asc, name asc){    _id,    _type,    name,    order,    logo {  _type,  asset,  alt,  caption,  crop,  hotspot}  }
export type AllPartnersQueryResult = Array<{
  _id: string;
  _type: "partner";
  name: string | null;
  order: number | null;
  logo: {
    _type: "image";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: null;
    caption: null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;
// Variable: allDoctorsQuery
// Query: *[_type == "doctor"] | order(order asc, name asc){    _id,    _type,    name,    shortName,    title,    bio,    registrationNumber,    registryUrl,    order,    photo {  _type,  asset,  alt,  caption,  crop,  hotspot}  }
export type AllDoctorsQueryResult = Array<{
  _id: string;
  _type: "doctor";
  name: string | null;
  shortName: string | null;
  title: string | null;
  bio: Array<string> | null;
  registrationNumber: string | null;
  registryUrl: string | null;
  order: number | null;
  photo: {
    _type: "imageWithAlt";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    alt: string | null;
    caption: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;
// Variable: allTestimonialsQuery
// Query: *[_type == "testimonial"] | order(order asc, name asc){    _id,    _type,    name,    quote,    source,    featured,    order,    "treatmentSlugs": treatments[]->slug.current  }
export type AllTestimonialsQueryResult = Array<{
  _id: string;
  _type: "testimonial";
  name: string | null;
  quote: string | null;
  source: "Fresha" | "Google" | "Other" | null;
  featured: boolean | null;
  order: number | null;
  treatmentSlugs: Array<string | null> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"page\" && path == $path][0]{\n    _id,\n    _type,\n    title,\n    path,\n    seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  noIndex\n},\n    sections[] {\n  ...,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  images[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  items[]{\n    ...,\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n}\n  }\n}\n  }\n": PageByPathQueryResult;
    "\n  *[_type == \"page\" && defined(path)].path\n": AllPagePathsQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    coverImage {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n    publishedAt,\n    \"categories\": categories[]->{_id, title, \"slug\": slug.current},\n    body,\n    seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  noIndex\n}\n  }\n": PostBySlugQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    coverImage {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n    publishedAt,\n    \"categories\": categories[]->{_id, title, \"slug\": slug.current},\n    body,\n    seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  noIndex\n}\n  }\n": AllPostsQueryResult;
    "\n  *[_type == \"post\" && defined(slug.current)].slug.current\n": AllPostSlugsQueryResult;
    "\n  *[_type == \"treatment\" && defined(slug.current)] | order(name asc){\n    ...,\n    \"slug\": slug.current,\n    image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n    seo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  noIndex\n}\n  }\n": AllTreatmentsQueryResult;
    "\n  *[_type == \"pricingSection\"] | order(order asc, title asc){\n    _id,\n    _type,\n    title,\n    category,\n    order,\n    groups\n  }\n": AllPricingSectionsQueryResult;
    "\n  *[_id == \"siteSettings\"][0]{\n    ...,\n    defaultSeo {\n  title,\n  description,\n  image {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n},\n  noIndex\n}\n  }\n": SiteSettingsQueryResult;
    "\n  *[_id == \"page.before-after\"][0].sections[_type == \"gallerySection\"]{\n    anchor,\n    images[] {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n}\n  }\n": ResultGalleriesQueryResult;
    "\n  *[_type == \"partner\"] | order(order asc, name asc){\n    _id,\n    _type,\n    name,\n    order,\n    logo {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n}\n  }\n": AllPartnersQueryResult;
    "\n  *[_type == \"doctor\"] | order(order asc, name asc){\n    _id,\n    _type,\n    name,\n    shortName,\n    title,\n    bio,\n    registrationNumber,\n    registryUrl,\n    order,\n    photo {\n  _type,\n  asset,\n  alt,\n  caption,\n  crop,\n  hotspot\n}\n  }\n": AllDoctorsQueryResult;
    "\n  *[_type == \"testimonial\"] | order(order asc, name asc){\n    _id,\n    _type,\n    name,\n    quote,\n    source,\n    featured,\n    order,\n    \"treatmentSlugs\": treatments[]->slug.current\n  }\n": AllTestimonialsQueryResult;
  }
}
